import React from "react";

import Link from "next/link";

export const metadata = {
  title: "ISTAD - Products",
  description: "Generated by create next app",
};

async function fetchProducts() {
  const resp = await fetch("https://fakestoreapi.com/products", {
    cache: "no-store",
  });
  return resp.json();
}

export default async function Products() {
  const products = await fetchProducts();
  return (
    <div className="container">
      <div className="row g-4">
        <h1 style={{ color: "blue", textAlign: "center" }}>
          Product Management
        </h1>
        {products.map((product) => (
          <div className="col-12 col-sm-6 col-md-4">
            <Link href={`/products/${product.id}`} className="text-decoration-none">
              <div class="card " style={{height: "500px", textAlign:"center"}}>
                <img src={product.image} class="card-img-top" alt="..." style={{height: "350px", width:"300px"}}/>
                <div class="card-body" style={{height: "150px"}}>
                  <h5 class="card-text">
                    {product.title}
                  </h5>
                </div>
              </div>
            </Link>
          </div>
        ))}
      </div>
    </div>
  );
}
